In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification

In [40]:
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2)
X.shape, y.shape

((1000, 20), (1000,))

In [41]:
np.unique(y)

array([0, 1])

In [42]:
# X = np.hstack([np.ones((1000, 1)), X]) # to add intercept

In [43]:
np.sum(X[:, 0] - X[:, 1])

-9.439620559305334

In [44]:
X.mean(axis=0), X.std(axis=0)

(array([ 0.00770717,  0.01714679,  0.02659486,  0.02150875,  0.02329381,
         0.04786348,  0.0348178 , -0.01446054, -0.01636471,  0.01029058,
        -0.03648658, -0.01421281, -0.04032865, -0.00062538,  0.05637915,
        -0.00898243, -0.03334624,  0.01723628,  0.02209461,  0.01517449]),
 array([1.00470729, 0.95741826, 1.02479061, 1.0090042 , 1.20125942,
        1.01601686, 0.99051917, 1.04935525, 0.99793196, 1.01547641,
        1.00088223, 0.99327932, 1.00045558, 1.00081805, 0.97761057,
        0.97433749, 1.01645018, 1.16609765, 1.31199651, 0.98950134]))

In [66]:
class Logreg:
    def __init__(self, learning_rate=0.1, iterations=1500, C=1.0):
        self.learning_rate = learning_rate
        self.iterations = iterations
        self.C = C
        self.weights = None
        self.intercept = None
        
        # history
        self.iters_list = []
        self.loss_list = []
    
    def fit(self, X, y):
        # number of observations
        n = len(y)
        # number of features
        k = X.shape[1]
        
        # 1. Initialize weights
        self.weights = np.zeros(k)
        self.intercept = 0
        
        for iteration in range(self.iterations):
            # 2 Predict
            z = np.dot(X, self.weights) + self.intercept
            y_hat = 1 / (1 + np.exp(-z))
            # 3 Calculate logloss
            #logloss = np.sum(-y * np.log(y_hat) - (1 - y) * np.log(1 - y_hat))
            logloss = np.sum(np.log(1 + np.exp(- y * y_hat)))
        
            # 4 Derivative by weights
            derivative_weights = (1 / n) * np.dot(X.T, (y_hat - y)) # (a - y) * x
            derivative_intercept = (1 / n) * np.sum(y_hat - y)

            # 5 Update weights
            self.weights -= self.learning_rate * (derivative_weights + self.C * self.weights)
            self.intercept -= self.learning_rate * (derivative_intercept + self.C * self.intercept)
            
            #print('Iteration:', iteration, 'Total logLoss =', logloss)
            
            # history update
            self.iters_list.append(iteration)
            self.loss_list.append(logloss)
            # 6 Repeat
    

    def predict(self, X):
        z = np.dot(X, self.weights) + self.intercept
        pred = 1 / (1 + np.exp(-z))
        return [1 if i > 0.5 else 0 for i in pred]


In [67]:
#weights = np.array([2, 3, 1])
#X = np.matrix([[1, 2, 3], [2, 2, 2], [3, 2, 3], [1, 1, 1]])

In [68]:
#np.exp(np.sum(np.dot(X, weights)))

In [69]:
logreg = Logreg(C=1.0)

In [70]:
logreg.fit(X, y)

In [71]:
mine_pred = logreg.predict(X)

In [72]:
np.unique(mine_pred)

array([0, 1])

## Sklearn

In [73]:
from sklearn.linear_model import LogisticRegression

In [74]:
lr = LogisticRegression(C=1.0, solver='liblinear')

In [75]:
lr.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [76]:
lr.intercept_

array([0.1635636])

In [77]:
lr.coef_

array([[-0.16292115,  1.39311248, -0.00230868,  0.38800679,  1.76940081,
         0.07627962,  0.13542552, -0.25980743,  0.08027389, -0.12907094,
         0.09251899, -0.15240749,  0.06719323,  0.05293899, -0.00653164,
        -0.16819577,  0.10599916,  1.61997867,  0.34919447,  0.05742598]])

In [78]:
pred = lr.predict(X)

In [79]:
y.shape, pred.shape

((1000,), (1000,))

In [80]:
np.unique(y), np.unique(pred)

(array([0, 1]), array([0, 1]))

## Comparison: Mine VS Sklearn

In [81]:
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix

In [82]:
accuracy_score(y, pred), roc_auc_score(y, pred)

(0.943, 0.9429950879214067)

In [83]:
accuracy_score(y, mine_pred), roc_auc_score(y, mine_pred)

(0.941, 0.9409870557928928)

In [84]:
logreg.weights

array([-0.01306172,  0.22107755,  0.01496606,  0.01412987,  0.2770991 ,
        0.00479433,  0.01150668, -0.01283411,  0.00300509,  0.00187734,
        0.00140605, -0.00708802, -0.00271376,  0.00654446, -0.00279061,
       -0.01761404,  0.00381569,  0.26366547,  0.01205112,  0.0146762 ])